In [1]:
#!git clone https://github.com/Dampata/ENLiT_challenge.git
#%cd ENLiT_challenge/Data

Cloning into 'ENLiT_challenge'...
remote: Enumerating objects: 57, done.
remote: Counting objects: 100% (57/57), done.
remote: Compressing objects: 100% (42/42), done.
remote: Total 57 (delta 9), reused 20 (delta 2), pack-reused 0 (from 0)
Receiving objects: 100% (57/57), 2.99 MiB | 5.46 MiB/s, done.
Resolving deltas: 100% (9/9), done.
/Users/damienpantalos/Documents/ENLiT_challenge/Data/ENLiT_challenge/Data

In [3]:
import pandas as pd
import datetime as dt


# Step 1: Load your data 
df_scheinder_energy = pd.read_csv('Data/Consumption_production.csv',skiprows=1)  # Load all data 


df_scheinder_energy.head()
# Step 3: Add a default Year column (since you need a year for datetime conversion)
df_scheinder_energy['Year'] = 2023  # You can set this to whatever year you are working with
df_scheinder_energy = df_scheinder_energy.drop(index=0)  # Removes row with index 0

df_scheinder_energy

# Step 4: Ensure Month, Day, and Hour are integers (this step ensures proper formatting)
df_scheinder_energy['Month'] = df_scheinder_energy['Month'].astype(int)
df_scheinder_energy['Day'] = df_scheinder_energy['Day'].astype(int)
df_scheinder_energy['Hour'] = df_scheinder_energy['Hour'].astype(int)

# Step 5: Convert Hour = 24 to Hour = 00
df_scheinder_energy['Hour'] = df_scheinder_energy['Hour'].replace(24, 0)

# Step 6: Combine Year, Month, Day, and Hour into a 'timestamp' column
df_scheinder_energy['timestamp'] = pd.to_datetime(df_scheinder_energy[['Year', 'Month', 'Day', 'Hour']])
df_scheinder_energy = df_scheinder_energy[['timestamp', 'Year'] + [col for col in df_scheinder_energy.columns if col != 'timestamp' and col != 'Year']]

# Step 7: Delete the first 3 columns (Month, Day, Hour)
df_scheinder_energy = df_scheinder_energy.drop(df_scheinder_energy.columns[2:5], axis=1)

df_scheinder_energy = df_scheinder_energy.iloc[:, :7]
# Display the final DataFrame
df_scheinder_energy.head()

,timestamp,Year,SITE CONSUMPTION Grid supply (kWh),SITE CONSUMPTION Natural Gas (kWh),ONSITE SOLAR SYSTEM PRODUCTION (kWh),GRID (EEX) Price (€/MWh),NG (TTF) Price (€/MWh)
1,2023-01-01 01:00:00,2023,224.0,44.8,0.0,-1.2,0.6
2,2023-01-01 02:00:00,2023,280.0,56.0,0.0,-1.0,0.5
3,2023-01-01 03:00:00,2023,323.8,64.8,0.0,-3.7,1.8
4,2023-01-01 04:00:00,2023,262.5,52.5,0.0,-3.1,1.5
5,2023-01-01 05:00:00,2023,287.0,57.4,0.0,-3.8,1.9

In [8]:
df_scheinder_energy['demand']  = df_scheinder_energy['SITE CONSUMPTION Grid supply (kWh)'].astype(float)+df_scheinder_energy['SITE CONSUMPTION Natural Gas (kWh)'].astype(float)

df_scheinder_energy['Energy_not_covered']= df_scheinder_energy['demand'].astype(float)-df_scheinder_energy['ONSITE SOLAR SYSTEM PRODUCTION (kWh)'].astype(float)

# add wind energy of 1kW capacity
df_scheinder_energy['ONSITE WIND TURBINE PRODUCTION (kWh)'] = pd.read_csv('Data/wind_RN.csv',usecols=[2])

df_scheinder_energy.head(50)

,timestamp,Year,SITE CONSUMPTION Grid supply (kWh),SITE CONSUMPTION Natural Gas (kWh),ONSITE SOLAR SYSTEM PRODUCTION (kWh),GRID (EEX) Price (€/MWh),NG (TTF) Price (€/MWh),demand,Energy_not_covered,ONSITE WIND TURBINE PRODUCTION (kWh)
1,2023-01-01 01:00:00,2023,224.0,44.8,0.0,-1.2,0.6,268.8,268.8,0.305
2,2023-01-01 02:00:00,2023,280.0,56.0,0.0,-1.0,0.5,336.0,336.0,0.317
3,2023-01-01 03:00:00,2023,323.8,64.8,0.0,-3.7,1.8,388.6,388.6,0.316
4,2023-01-01 04:00:00,2023,262.5,52.5,0.0,-3.1,1.5,315.0,315.0,0.294
5,2023-01-01 05:00:00,2023,287.0,57.4,0.0,-3.8,1.9,344.4,344.4,0.317
6,2023-01-01 06:00:00,2023,234.5,46.9,0.0,-3.3,1.6,281.4,281.4,0.341
7,2023-01-01 07:00:00,2023,353.5,70.7,0.0,-0.9,0.5,424.2,424.2,0.360
8,2023-01-01 08:00:00,2023,236.3,47.3,0.0,-1.1,0.5,283.6,283.6,0.376
9,2023-01-01 09:00:00,2023,299.3,59.9,0.0,-0.7,0.4,359.2,359.2,0.383
10,2023-01-01 10:00:00,2023,302.8,60.6,10.6,-0.2,0.1,363.4,352.8,0.404
11,2023-01-01 11:00:00,2023,283.5,56.7,30.6,-0.5,0.3,340.2,309.6,0.400
12,2023-01-01 12:00:00,2023,253.8,50.8,80.1,-0.4,0.2,304.6,224.5,0.388
13,2023-01-01 13:00:00,2023,225.8,45.2,245.5,-0.1,0.0,271.0,25.5,0.394
14,2023-01-01 14:00:00,2023,257.3,51.5,260.2,0.6,0.3,308.8,48.6,0.391
15,2023-01-01 15:00:00,2023,358.8,71.8,133.0,16.5,8.2,430.6,297.6,0.421
16,2023-01-01 16:00:00,2023,264.3,52.9,35.9,25.6,12.8,317.2,281.3,0.411
17,2023-01-01 17:00:00,2023,229.3,45.9,0.6,32.2,16.1,275.2,274.6,0.442
18,2023-01-01 18:00:00,2023,278.3,55.7,0.0,25.6,12.8,334.0,334.0,0.468
19,2023-01-01 19:00:00,2023,288.8,57.8,0.0,38.5,19.2,346.6,346.6,0.479
20,2023-01-01 20:00:00,2023,231.0,46.2,0.0,32.1,16.0,277.2,277.2,0.481
21,2023-01-01 21:00:00,2023,301.0,60.2,0.0,25.6,12.8,361.2,361.2,0.488
22,2023-01-01 22:00:00,2023,304.5,60.9,0.0,32.2,16.1,365.4,365.4,0.491
23,2023-01-01 23:00:00,2023,271.3,54.3,0.0,24.5,12.3,325.6,325.6,0.502
24,2023-01-01 00:00:00,2023,269.5,53.9,0.0,48.9,24.5,323.4,323.4,0.532
25,2023-01-02 01:00:00,2023,227.5,45.5,0.0,41.4,20.7,273.0,273.0,0.539
26,2023-01-02 02:00:00,2023,287.0,57.4,0.0,37.1,18.5,344.4,344.4,0.516
27,2023-01-02 03:00:00,2023,323.8,64.8,0.0,29.8,14.9,388.6,388.6,0.507
28,2023-01-02 04:00:00,2023,243.3,48.7,0.0,35.1,17.5,292.0,292.0,0.518
29,2023-01-02 05:00:00,2023,299.3,59.9,0.0,48.8,24.4,359.2,359.2,0.513
30,2023-01-02 06:00:00,2023,234.5,46.9,0.0,73.6,36.8,281.4,281.4,0.516
31,2023-01-02 07:00:00,2023,325.5,65.1,0.0,98.4,49.2,390.6,390.6,0.484
32,2023-01-02 08:00:00,2023,248.5,49.7,0.0,106.3,53.2,298.2,298.2,0.367
33,2023-01-02 09:00:00,2023,304.5,60.9,0.0,111.2,55.6,365.4,365.4,0.291
34,2023-01-02 10:00:00,2023,288.8,57.8,19.4,101.9,51.0,346.6,327.2,0.407
35,2023-01-02 11:00:00,2023,295.8,59.2,65.9,100.3,50.2,355.0,289.1,0.446
36,2023-01-02 12:00:00,2023,196.0,39.2,93.6,101.1,50.5,235.2,141.6,0.386
37,2023-01-02 13:00:00,2023,316.8,63.4,104.2,100.6,50.3,380.2,276.0,0.302
38,2023-01-02 14:00:00,2023,245.0,49.0,131.3,103.7,51.9,294.0,162.7,0.332
39,2023-01-02 15:00:00,2023,332.5,66.5,80.6,108.7,54.4,399.0,318.4,0.364
40,2023-01-02 16:00:00,2023,295.8,59.2,42.4,114.3,57.2,355.0,312.6,0.345
41,2023-01-02 17:00:00,2023,245.0,49.0,7.7,123.1,61.5,294.0,286.3,0.314
42,2023-01-02 18:00:00,2023,299.3,59.9,0.0,122.3,61.2,359.2,359.2,0.273
43,2023-01-02 19:00:00,2023,271.3,54.3,0.0,116.5,58.3,325.6,325.6,0.234
44,2023-01-02 20:00:00,2023,267.8,53.6,0.0,107.1,53.6,321.4,321.4,0.200
45,2023-01-02 21:00:00,2023,327.3,65.5,0.0,99.2,49.6,392.8,392.8,0.167
46,2023-01-02 22:00:00,2023,323.8,64.8,0.0,94.4,47.2,388.6,388.6,0.140
47,2023-01-02 23:00:00,2023,245.0,49.0,0.0,87.0,43.5,294.0,294.0,0.124
48,2023-01-02 00:00:00,2023,250.3,50.1,0.0,91.0,45.5,300.4,300.4,0.112
49,2023-01-03 01:00:00,2023,246.8,49.4,0.0,84.0,42.0,296.2,296.2,0.111
50,2023-01-03 02:00:00,2023,276.5,55.3,0.0,83.1,41.6,331.8,331.8,0.116